// Generated by CoffeeScript 1.8.0

/*
    Poe.GUI.Editor a wrapper around Poe.Document in order for the program to be usable by
    a window.
 */

(function() {
  var Application, ApplicationPoe, ApplicationPoeWindow, Window;

  window.Poe = window.Poe || {};

  Poe.OSjs = {};

  Application = OSjs.Helpers.DefaultApplication;

  Window = OSjs.Helpers.DefaultApplicationWindow;

  ApplicationPoeWindow = function(app, metadata) {
    return Window.apply(this, [
      'ApplicationPoeWindow', {
        icon: metadata.icon,
        title: metadata.name,
        allow_drop: false,
        width: 800,
        height: 450
      }, app
    ]);
  };

  ApplicationPoeWindow.prototype = Object.create(Window.prototype);

  ApplicationPoeWindow.prototype.init = function(vmRef, app) {
    var onResize, root, toolbar;
    root = Window.prototype.init.apply(this, arguments);
    this.Poe = new Poe.Writer(root);
    toolbar = this._addGUIElement(new Poe.OSjs.Toolbar(this.Poe, this, 'PoeToolbar'), root);
    onResize = (function(_this) {
      return function() {
        var elm, heights, wrapper, _i, _len, _ref;
        wrapper = _this.Poe.element.parents('.WindowWrapper');
        heights = 0;
        console.log(_this.Poe.element.parent().children());
        _ref = _this.Poe.element.parent().children();
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          elm = _ref[_i];
          if (elm === _this.Poe.element[0]) {
            continue;
          }
          heights += $(elm).outerHeight();
        }
        _this.Poe.element.css('height', (wrapper.height() - heights) + 'px');
        _this.Poe.document.textCursor.show();
        return $('.visiblecursor').css('z-index', "" + (_this._getZindex() + 1));
      };
    })(this);

    /*
    These are some OSjs specific things. It has to do with
     */
    this._addHook('resize', onResize);
    this._addHook('maximize', onResize);
    this._addHook('restore', onResize);
    this._addHook('minimize', this.Poe.document.textCursor.hide());
    this._addHook('restore', this.Poe.document.textCursor.show());
    this._addHook('blur', this.Poe.document.textCursor.hide());
    this._addHook('focus', this.Poe.document.textCursor.show());
    this.Poe.element.before($(toolbar.$container.parentElement));
    onResize();
    return root;
  };

  ApplicationPoe = function(args, metadata) {
    return Application.apply(this, ['ApplicationPoe', args, metadata]);
  };

  ApplicationPoe.prototype = Object.create(Application.prototype);

  ApplicationPoe.prototype.init = function(settings, metadata) {
    this.mainWindow = this._addWindow(new ApplicationPoeWindow(this, metadata));
    return Application.prototype.init.apply(this, arguments);
  };

  OSjs.Applications.ApplicationPoe = ApplicationPoe;

}).call(this);

//# sourceMappingURL=main.js.map
