// Generated by CoffeeScript 1.8.0

/*
A button group. This class is a wrapper around Bootstrap's button group, to try
to abstract away the DOM.
 */

(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Poe.ButtonGroup = (function(_super) {
    __extends(ButtonGroup, _super);


    /*
    Creates a {Poe.ButtonGroup} object
    
    @param toolbar [Poe.ToolBar] the toolbar to add this button group to
    @param buttons [array] an array of {Poe.Button} to add to the group
     */

    function ButtonGroup(toolbar, buttons) {
      this.handleRadio = __bind(this.handleRadio, this);
      var button, _i, _len;
      this.container = $('<div class="btn-group" role="group"></div>');
      toolbar.element.append(this.container);
      if (buttons) {
        for (_i = 0, _len = buttons.length; _i < _len; _i++) {
          button = buttons[_i];
          this.container.append(button.element());
        }
        this.buttons = buttons;
      } else {
        this.buttons = [];
      }
    }


    /*
    Get the element that is being used in the DOM
    @return [jQuery] A jQuery object for the button group
     */

    ButtonGroup.prototype.element = function() {
      return this.container;
    };


    /*
    Sets the buttons in this group to only have one active at a time. Like a group of radio
    checkboxes.
    
    @param radio [boolean] Turn radio on or off
     */

    ButtonGroup.prototype.setRadio = function(radio) {
      if (radio) {
        return this.container.on('click', 'button', this.handleRadio);
      } else {
        return this.container.off('click', 'button', this.handleRadio);
      }
    };


    /*
    Handles the radio style of the buttons if {Poe.ButtonGroup#setRadio} has been used.
    This is for internal use.
     */

    ButtonGroup.prototype.handleRadio = function(event) {
      var button, _i, _len, _ref, _results;
      _ref = this.buttons;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        button = _ref[_i];
        if (event.target === button.element()[0]) {
          _results.push(button.active(true));
        } else {
          _results.push(button.active(false));
        }
      }
      return _results;
    };

    return ButtonGroup;

  })(Poe.ToolBarItem);

}).call(this);

//# sourceMappingURL=ButtonGroup.js.map
