// Generated by CoffeeScript 1.8.0

/*
Poe.Document is the top and contains pages. It also manages
page margins and page size.
 */

(function() {
  Poe.Document = (function() {

    /*
    Create a new Poe.Document. Creating a document is only possible in {Poe.Writer}
    in order for it to be shown in the DOM.
     */
    function Document() {
      var margins;
      this.children = [];
      this.element = $('<div class="document"></div>');
      $('body').append(this.element);
      this.setPageSize(Poe.Document.PageSize.Letter);
      this.setPageMargins(margins = {
        top: 96,
        bottom: 96,
        left: 96,
        right: 96
      });
      this.pdf = new Poe.PDF(this);
      this.append(new Poe.Page());
      this.textCursor = new Poe.TextCursor(this.children[0].child(0).child(0).child(0));
    }


    /*
    Gets the child page at index.
    @param index [Number] index to retrieve
    @return [null] if the page does not exist
    @return [Poe.Page] if the page exists
     */

    Document.prototype.page = function(index) {
      if (index >= 0 && index < this.children.length) {
        return this.children[index];
      }
      return null;
    };


    /*
    Append a page to the end of the document.
    @param page [Poe.Page] the page to append
     */

    Document.prototype.append = function(page) {
      page.document = this;
      this.children.append(page);
      this.element.append(page.element);
      page.setParent(this);
      this.setPageMargins(this.margins);
      this.setPageSize(this.pageSize);
      return this;
    };


    /*
    Prepend a page to the front of the document.
    @param page [Poe.Page] the page to prepend
    @return [Poe.Document] this
     */

    Document.prototype.prepend = function(page) {
      page.document = this;
      this.children.prepend(page);
      this.element.prepend(page.element);
      page.setParent(this);
      this.setPageMargins(this.margins);
      this.setPageSize(this.pageSize);
      return this;
    };


    /*
    Sets the page size to size
    @param size [Object] the size object
    @option size [Number] width the width in pixels
    @option size [Number] height the height in pixels
    @return [Poe.Document] this
     */

    Document.prototype.setPageSize = function(size) {
      var page, _i, _len, _ref;
      _ref = this.children;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        page = _ref[_i];
        page.element.css('height', "" + size.height);
        page.element.css('width', "" + size.width);
      }
      this.pageSize = size;
      if (this.textCursor) {
        this.textCursor.show();
      }
      return this;
    };


    /*
    Sets the page margins for all pages.
    @param margins [Poe.Document.PageSize] the size
    @return [Poe.Document] this
     */

    Document.prototype.setPageMargins = function(margins) {
      var page, _i, _len, _ref;
      _ref = this.children;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        page = _ref[_i];
        page.element.css('padding-left', margins.left);
        page.element.css('padding-right', margins.right);
        page.element.css('padding-top', margins.top);
        page.element.css('padding-bottom', margins.bottom);
      }
      this.margins = margins;
      if (this.textCursor) {
        this.textCursor.show();
      }
      return this;
    };


    /*
    Gets a {Poe.TextObject} for the jQuery object specified. This function recursively searches
    all {Poe.TextObject}'s in the document tree. If it finds an object that is for the element it 
    returns it, otherwise returns null.
    
    @return [Poe.TextObject] The object that was found, or null otherwise.
    
    @param element [jQuery] the element to find
     */

    Document.prototype.objectFromElement = function(element) {
      var page, ret, _i, _len, _ref;
      _ref = this.children;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        page = _ref[_i];
        if (page.element[0] === element[0]) {
          return page;
        }
        ret = page.fromElement(element);
        if (ret !== null) {
          return ret;
        }
      }
      return null;
    };


    /*
    "Enum" of possible page sizes
     */

    Document.PageSize = {
      Letter: {
        height: 1056,
        width: 816
      },
      Legal: {
        width: 8.5 * 96,
        height: 14 * 96
      },
      Ledger: {
        width: 17 * 96,
        height: 11 * 96
      },
      Tabloid: {
        width: 11 * 96,
        height: 17 * 96
      }
    };

    return Document;

  })();

}).call(this);

//# sourceMappingURL=Document.js.map
