// Generated by CoffeeScript 1.8.0
(function() {
  Poe.DocxReader = (function() {
    function DocxReader(document) {
      this.document = document;
      this.file = null;
    }

    DocxReader.prototype.open = function(file) {};

    return DocxReader;

  })();

}).call(this);

//# sourceMappingURL=DocxReader.js.map
