// Generated by CoffeeScript 1.8.0

/*
Some keycodes that are of importance to Poe for shortcuts and what not
 */

(function() {
  Poe.key = {
    Space: 32,
    Backspace: 8,
    Delete: 46,
    Enter: 13,
    Left: 37,
    Right: 39,
    Up: 38,
    Down: 40,
    Tab: 9,
    B: 66,
    I: 73,
    U: 85,
    Shift: 16,
    CapsLock: 20
  };

}).call(this);

//# sourceMappingURL=Keymap.js.map
