// Generated by CoffeeScript 1.8.0

/*
Poe.List is a Poe.Paragraph subclass for bulleted or numbered lists.
Instead of a {Poe.Line}, it takes a {Poe.ListItem} as a child. However note
that a {Poe.Line} could be added as a child if no bullet or number is wanted.
 */

(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Poe.List = (function(_super) {
    __extends(List, _super);


    /*
    Creates a new Poe.List
     */

    function List() {
      var li, listType;
      this.element = $('<ul class="list"></ul>');
      this.children = [];
      $('body').append(this.element);
      li = new Poe.ListItem();
      this.append(li);
      listType = Poe.List.ListType.Bullets;
    }


    /*
    Sets the list bullet type.
    @param type [Poe.List.ListType] the bullet type
    @return [Poe.List] this
     */

    List.prototype.setListType = function(type) {
      if (type == null) {
        type = Poe.List.ListType.Bullets;
      }
      this.element.css('list-style-type', type);
      this.listType = type;
      return this;
    };


    /*
    Bullet types for use with {Poe.List#setListType}
     */

    List.ListType = {
      Bullets: 'disc',
      Numbers: 'decimal'
    };

    return List;

  })(Poe.Paragraph);

}).call(this);

//# sourceMappingURL=List.js.map
