// Generated by CoffeeScript 1.8.0

/*
Poe.ListItem is a extension of Poe.Line for numbered or bulleted lists.
It works with {Poe.List} to provide them. A {Poe.Line} could be used
in place of this if you would like a line to be added to the list without
a bullet or number, eg. for more than one line in a list item.
 */

(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Poe.ListItem = (function(_super) {
    __extends(ListItem, _super);


    /*
    Creates a new Poe.ListItem
     */

    function ListItem() {
      var word;
      this.element = $('<li></li>');
      this.children = [];
      word = new Poe.Word();
      this.append(word);
    }

    return ListItem;

  })(Poe.Line);

}).call(this);

//# sourceMappingURL=ListItem.js.map
