// Generated by CoffeeScript 1.8.0

/*
Poe.Page is just a container to hold paragraphs. Or any other
similar object.
 */

(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Poe.Page = (function(_super) {
    __extends(Page, _super);


    /*
    Create a new Poe.Page. This also creates a new {Poe.Paragraph} as a child.
     */

    function Page(document) {
      this.children = [];
      this.element = $('<div class="page"></div>');
      $('body').append(this.element);
      this.setParent(document);
      this.append(new Poe.Paragraph());
    }


    /*
    Inserts this page after another {Poe.Page}
    
    @param page [Poe.Page] the page to insert after
     */

    Page.prototype.insertAfter = function(page) {
      Page.__super__.insertAfter.call(this, page);
      this.parent.setPageSize(this.parent.pageSize);
      return this.parent.setPageMargins(this.parent.margins);
    };

    return Page;

  })(Poe.TextObject);

}).call(this);

//# sourceMappingURL=Page.js.map
