// Generated by CoffeeScript 1.8.0
(function() {
  window.Poe = window.Poe || {};

  Poe.FileFormat = Poe.FileFormat || {};


  /*
  $(document).ready ->
    Poe.writer = new Poe.Writer('#Poe')
    $('.poe-tooltip').tooltip()
   */

  if (!Array.prototype.last) {
    Array.prototype.last = function() {
      return this[this.length - 1];
    };
  }

  if (!Array.prototype.first) {
    Array.prototype.first = function() {
      return this[0];
    };
  }

  if (!Array.prototype.insertBefore) {
    Array.prototype.insertBefore = function(insert, before) {
      var index;
      index = this.indexOf(before);
      if (index !== -1) {
        this.splice(index, 0, insert);
        return true;
      }
      return false;
    };
  }

  if (!Array.prototype.insertAfter) {
    Array.prototype.insertAfter = function(insert, after) {
      var index;
      index = this.indexOf(after);
      if (index !== -1) {
        if (index === this.length) {
          this.append(insert);
        }
        this.splice(index + 1, 0, insert);
        return true;
      }
      return false;
    };
  }

  if (!Array.prototype.append) {
    Array.prototype.append = function(item) {
      this[this.length] = item;
      return this;
    };
  }

  if (!Array.prototype.prepend) {
    Array.prototype.prepend = function(item) {
      this.splice(0, 0, item);
      return this;
    };
  }

  if (!Array.prototype.next) {
    Array.prototype.next = function(after) {
      var index;
      index = this.indexOf(after);
      if (this.length - 1 >= index + 1) {
        return this[index + 1];
      }
      return null;
    };
  }

  if (!Array.prototype.prev) {
    Array.prototype.prev = function(before) {
      var index;
      index = this.indexOf(before);
      if (this.length > 0) {
        return this[index - 1];
      }
      return null;
    };
  }

  if (!Array.prototype.remove) {
    Array.prototype.remove = function(item) {
      var index;
      index = this.indexOf(item);
      return this.splice(index, 1);
    };
  }

  if (!Array.prototype.last) {
    Array.prototype.last = function() {
      if (this.length > 0) {
        return this[this.length - 1];
      }
      return null;
    };
  }

  if (!Array.prototype.first) {
    Array.prototype.first = function() {
      if (this.length > 0) {
        return this[0];
      }
      return null;
    };
  }

  if (!Array.prototype.contains) {
    Array.prototype.contains = function(item) {
      return this.indexOf(item) !== -1;
    };
  }

  $.fn.prevSibling = function() {
    var sibling;
    sibling = $(this[0].previousSibling);
    if (sibling.length !== 0) {
      return sibling;
    }
    return null;
  };

  $.fn.nextSibling = function() {
    var sibling;
    sibling = $(this[0].nextSibling);
    if (sibling.length !== 0) {
      return sibling;
    }
    return null;
  };

}).call(this);

//# sourceMappingURL=Poe.js.map
