// Generated by CoffeeScript 1.8.0

/*
Poe.Writer is the only thing you need to use in order to add Poe to your webpage.
It handles everything else.

@example index.html
  ...
  <div id="Poe"></div>

  <script type="text/javascript">
  poe = new Poe.Writer("#Poe");
  </script>
 */

(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Poe.Writer = (function() {

    /*
    Create a new Poe.Writer instance.
    @param parentSelector [CSS] The css selector to use with jQuery to find
    your element.
     */
    function Writer(parentSelector) {
      this.windowResized = __bind(this.windowResized, this);
      this.document = new Poe.Document();
      this.element = $('<div class="writer"></div>');
      if (!parentSelector) {
        $('body').append(this.element);
      } else {
        $(parentSelector).append(this.element);
      }
      this.element.append(this.document.element);
      this.toolbarHelper = new Poe.ToolbarHelper(this);
      if (!Poe.OSjs) {
        this.toolbar = new Poe.ToolBar(this);
      }
      $('body').resize(this.windowResized);
      this.element.scroll(this.windowResized);
      this.windowResized();
    }


    /*
    Event handler when the window resizes. Updates the writers width and height
    @private
     */

    Writer.prototype.windowResized = function(event) {
      if (!Poe.OSjs) {
        this.element.css('width', $('body').width());
        this.element.css('height', $('body').height() - this.toolbar.element.height());
      }
      return this.document.textCursor.update();
    };

    return Writer;

  })();

}).call(this);

//# sourceMappingURL=Writer.js.map
